package com.github.Redux.iceandfire.client.render.entity;

import com.github.Redux.iceandfire.block.IafBlockRegistry;
import com.github.Redux.iceandfire.client.model.ModelMyrmexQueen;
import com.github.Redux.iceandfire.client.model.ModelMyrmexRoyal;
import com.github.Redux.iceandfire.client.model.ModelMyrmexSentinel;
import com.github.Redux.iceandfire.client.model.ModelMyrmexSoldier;
import com.github.Redux.iceandfire.client.model.ModelMyrmexWorker;
import com.github.Redux.iceandfire.client.model.animator.FireDragonTabulaModelAnimator;
import com.github.Redux.iceandfire.client.model.animator.IceDragonTabulaModelAnimator;
import com.github.Redux.iceandfire.client.model.animator.LightningDragonTabulaModelAnimator;
import com.github.Redux.iceandfire.client.model.animator.SeaSerpentTabulaModelAnimator;
import com.github.Redux.iceandfire.client.model.util.EnumDragonAnimations;
import com.github.Redux.iceandfire.client.model.util.EnumSeaSerpentAnimations;
import com.github.Redux.iceandfire.client.model.util.IceAndFireTabulaModel;
import com.github.Redux.iceandfire.client.render.tile.RenderEggInIce;
import com.github.Redux.iceandfire.client.render.tile.RenderGhostChest;
import com.github.Redux.iceandfire.client.render.tile.RenderGorgonHead;
import com.github.Redux.iceandfire.client.render.tile.RenderJar;
import com.github.Redux.iceandfire.client.render.tile.RenderLectern;
import com.github.Redux.iceandfire.client.render.tile.RenderMobSpawner;
import com.github.Redux.iceandfire.client.render.tile.RenderPixieHouse;
import com.github.Redux.iceandfire.client.render.tile.RenderPodium;
import com.github.Redux.iceandfire.entity.EntityAmphithere;
import com.github.Redux.iceandfire.entity.EntityBlackFrostDragon;
import com.github.Redux.iceandfire.entity.EntityCockatrice;
import com.github.Redux.iceandfire.entity.EntityCyclops;
import com.github.Redux.iceandfire.entity.EntityDeathWorm;
import com.github.Redux.iceandfire.entity.EntityDragonEgg;
import com.github.Redux.iceandfire.entity.EntityDragonSkull;
import com.github.Redux.iceandfire.entity.EntityDreadBeast;
import com.github.Redux.iceandfire.entity.EntityDreadGhoul;
import com.github.Redux.iceandfire.entity.EntityDreadHorse;
import com.github.Redux.iceandfire.entity.EntityDreadKnight;
import com.github.Redux.iceandfire.entity.EntityDreadLich;
import com.github.Redux.iceandfire.entity.EntityDreadQueen;
import com.github.Redux.iceandfire.entity.EntityDreadScuttler;
import com.github.Redux.iceandfire.entity.EntityDreadThrall;
import com.github.Redux.iceandfire.entity.EntityFireDragon;
import com.github.Redux.iceandfire.entity.EntityGhost;
import com.github.Redux.iceandfire.entity.EntityGhostSword;
import com.github.Redux.iceandfire.entity.EntityGorgon;
import com.github.Redux.iceandfire.entity.EntityHippocampus;
import com.github.Redux.iceandfire.entity.EntityHippogryph;
import com.github.Redux.iceandfire.entity.EntityHydra;
import com.github.Redux.iceandfire.entity.EntityIceDragon;
import com.github.Redux.iceandfire.entity.EntityLightningDragon;
import com.github.Redux.iceandfire.entity.EntityMobSkull;
import com.github.Redux.iceandfire.entity.EntityMyrmexEgg;
import com.github.Redux.iceandfire.entity.EntityMyrmexQueen;
import com.github.Redux.iceandfire.entity.EntityMyrmexRoyal;
import com.github.Redux.iceandfire.entity.EntityMyrmexSentinel;
import com.github.Redux.iceandfire.entity.EntityMyrmexSoldier;
import com.github.Redux.iceandfire.entity.EntityMyrmexSwarmer;
import com.github.Redux.iceandfire.entity.EntityMyrmexWorker;
import com.github.Redux.iceandfire.entity.EntityPixie;
import com.github.Redux.iceandfire.entity.EntitySeaSerpent;
import com.github.Redux.iceandfire.entity.EntityShivaxiDragon;
import com.github.Redux.iceandfire.entity.EntitySiren;
import com.github.Redux.iceandfire.entity.EntitySnowVillager;
import com.github.Redux.iceandfire.entity.EntityStoneStatue;
import com.github.Redux.iceandfire.entity.EntityStymphalianBird;
import com.github.Redux.iceandfire.entity.EntityTroll;
import com.github.Redux.iceandfire.entity.projectile.EntityAmphithereArrow;
import com.github.Redux.iceandfire.entity.projectile.EntityCockatriceEgg;
import com.github.Redux.iceandfire.entity.projectile.EntityDeathWormEgg;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonArrow;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonBreath;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonFire;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonFireCharge;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonIce;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonIceCharge;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonLightning;
import com.github.Redux.iceandfire.entity.projectile.EntityDragonLightningCharge;
import com.github.Redux.iceandfire.entity.projectile.EntityDreadLichSkull;
import com.github.Redux.iceandfire.entity.projectile.EntityHippogryphEgg;
import com.github.Redux.iceandfire.entity.projectile.EntityHydraArrow;
import com.github.Redux.iceandfire.entity.projectile.EntityHydraBreath;
import com.github.Redux.iceandfire.entity.projectile.EntitySeaSerpentArrow;
import com.github.Redux.iceandfire.entity.projectile.EntitySeaSerpentBubbles;
import com.github.Redux.iceandfire.entity.projectile.EntityShivaxiDragonLightning;
import com.github.Redux.iceandfire.entity.projectile.EntityStymphalianArrow;
import com.github.Redux.iceandfire.entity.projectile.EntityStymphalianFeather;
import com.github.Redux.iceandfire.entity.projectile.EntityTideTrident;
import com.github.Redux.iceandfire.entity.tile.TileEntityDummyGorgonHead;
import com.github.Redux.iceandfire.entity.tile.TileEntityDummyGorgonHeadActive;
import com.github.Redux.iceandfire.entity.tile.TileEntityDreadSpawner;
import com.github.Redux.iceandfire.entity.tile.TileEntityEggInIce;
import com.github.Redux.iceandfire.entity.tile.TileEntityGhostChest;
import com.github.Redux.iceandfire.entity.tile.TileEntityJar;
import com.github.Redux.iceandfire.entity.tile.TileEntityLectern;
import com.github.Redux.iceandfire.entity.tile.TileEntityMonsterSpawner;
import com.github.Redux.iceandfire.entity.tile.TileEntityPixieHouse;
import com.github.Redux.iceandfire.entity.tile.TileEntityPodium;
import com.github.Redux.iceandfire.item.IafItemRegistry;
import net.ilexiconn.llibrary.client.model.tabula.TabulaModelHandler;
import net.minecraft.client.Minecraft;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.renderer.entity.RenderSnowball;
import net.minecraft.item.Item;
import net.minecraftforge.client.ForgeHooksClient;
import net.minecraftforge.fml.client.registry.ClientRegistry;
import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import java.io.IOException;

/** Entidad Render Registry */

@SideOnly(Side.CLIENT)
public final class EntityRenderRegistry {

	private EntityRenderRegistry() {}

	@SideOnly(Side.CLIENT)
	public static void registerAll() {
		EnumDragonAnimations.initializeDragonModels();
		EnumSeaSerpentAnimations.initializeSerpentModels();
		ModelBase firedragon_model = null;
		ModelBase icedragon_model = null;
		ModelBase lightningdragon_model = null;
		ModelBase seaserpent_model = null;

		try {
			firedragon_model = new IceAndFireTabulaModel(TabulaModelHandler.INSTANCE.loadTabulaModel("/assets/iceandfire/models/tabula/firedragon/dragonFireGround"), new FireDragonTabulaModelAnimator());
			icedragon_model = new IceAndFireTabulaModel(TabulaModelHandler.INSTANCE.loadTabulaModel("/assets/iceandfire/models/tabula/icedragon/dragonIceGround"), new IceDragonTabulaModelAnimator());
			lightningdragon_model = new IceAndFireTabulaModel(TabulaModelHandler.INSTANCE.loadTabulaModel("/assets/iceandfire/models/tabula/lightningdragon/dragonLightningGround"), new LightningDragonTabulaModelAnimator());
			seaserpent_model = new IceAndFireTabulaModel(TabulaModelHandler.INSTANCE.loadTabulaModel("/assets/iceandfire/models/tabula/seaserpent/seaserpent"), new SeaSerpentTabulaModelAnimator());
		} catch (IOException e) {
			e.printStackTrace();
		}
		RenderingRegistry.registerEntityRenderingHandler(EntityFireDragon.class, new RenderDragonBase(Minecraft.getMinecraft().getRenderManager(), firedragon_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityIceDragon.class, new RenderDragonBase(Minecraft.getMinecraft().getRenderManager(), icedragon_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityLightningDragon.class, new RenderDragonBase(Minecraft.getMinecraft().getRenderManager(), lightningdragon_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonEgg.class, new RenderDragonEgg(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonArrow.class, new RenderDragonArrow(Minecraft.getMinecraft().getRenderManager(), Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonSkull.class, new RenderDragonSkull(Minecraft.getMinecraft().getRenderManager(), firedragon_model, icedragon_model, lightningdragon_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonFire.class, new RenderNothing(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonIce.class, new RenderNothing(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonLightning.class, new RenderNothing(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonFireCharge.class, new RenderDragonFireCharge(Minecraft.getMinecraft().getRenderManager(), RenderDragonFireCharge.Type.FIRE));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonIceCharge.class, new RenderDragonFireCharge(Minecraft.getMinecraft().getRenderManager(), RenderDragonFireCharge.Type.ICE));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonLightningCharge.class, new RenderDragonFireCharge(Minecraft.getMinecraft().getRenderManager(), RenderDragonFireCharge.Type.LIGHTNING));
		RenderingRegistry.registerEntityRenderingHandler(EntitySnowVillager.class, new RenderSnowVillager(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityHippogryphEgg.class, new RenderSnowball<EntityHippogryphEgg>(Minecraft.getMinecraft().getRenderManager(), IafItemRegistry.hippogryph_egg, Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityHippogryph.class, new RenderHippogryph(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityStoneStatue.class, new RenderStoneStatue(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityGorgon.class, new RenderGorgon(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityPixie.class, new RenderPixie(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityCyclops.class, new RenderCyclops(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntitySiren.class, new RenderSiren(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityHippocampus.class, new RenderHippocampus(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDeathWorm.class, new RenderDeathWorm(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDeathWormEgg.class, new RenderDeathWormEgg(Minecraft.getMinecraft().getRenderManager(), Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityCockatrice.class, new RenderCockatrice(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityCockatriceEgg.class, new RenderSnowball<EntityCockatriceEgg>(Minecraft.getMinecraft().getRenderManager(), IafItemRegistry.rotten_egg, Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityStymphalianBird.class, new RenderStymphalianBird(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityStymphalianFeather.class, new RenderStymphalianFeather(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityStymphalianArrow.class, new RenderStymphalianArrow(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityTroll.class, new RenderTroll(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexWorker.class, new RenderMyrmexBase(Minecraft.getMinecraft().getRenderManager(), new ModelMyrmexWorker(), 0.5F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexSoldier.class, new RenderMyrmexBase(Minecraft.getMinecraft().getRenderManager(), new ModelMyrmexSoldier(), 0.75F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexQueen.class, new RenderMyrmexBase(Minecraft.getMinecraft().getRenderManager(), new ModelMyrmexQueen(), 1.25F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexEgg.class, new RenderMyrmexEgg(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexSentinel.class, new RenderMyrmexBase(Minecraft.getMinecraft().getRenderManager(), new ModelMyrmexSentinel(), 0.85F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexRoyal.class, new RenderMyrmexBase(Minecraft.getMinecraft().getRenderManager(), new ModelMyrmexRoyal(), 0.75F));
		RenderingRegistry.registerEntityRenderingHandler(EntityMyrmexSwarmer.class, new RenderMyrmexBase(Minecraft.getMinecraft().getRenderManager(), new ModelMyrmexRoyal(), 0.25F));
		RenderingRegistry.registerEntityRenderingHandler(EntityAmphithere.class, new RenderAmphithere(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityAmphithereArrow.class, new RenderAmphithereArrow(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaSerpent.class, new RenderSeaSerpent(Minecraft.getMinecraft().getRenderManager(), seaserpent_model));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaSerpentBubbles.class, new RenderNothing(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntitySeaSerpentArrow.class, new RenderSeaSerpentArrow(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityHydraArrow.class, new RenderHydraArrow(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityHydra.class, new RenderHydra(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityHydraBreath.class, new RenderNothing(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityTideTrident.class, new RenderTideTrident(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadThrall.class, new RenderDreadThrall(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadGhoul.class, new RenderDreadGhoul(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadBeast.class, new RenderDreadBeast(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadScuttler.class, new RenderDreadScuttler(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadLich.class, new RenderDreadLich(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadLichSkull.class, new RenderDreadLichSkull(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadKnight.class, new RenderDreadKnight(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadHorse.class, new RenderDreadHorse(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityBlackFrostDragon.class, new RenderBlackFrostDragon(Minecraft.getMinecraft().getRenderManager(), icedragon_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityDreadQueen.class, new RenderDreadQueen(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhost.class, new RenderGhost(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityGhostSword.class, new RenderGhostSword<>(Minecraft.getMinecraft().getRenderManager(), Minecraft.getMinecraft().getRenderItem()));
		RenderingRegistry.registerEntityRenderingHandler(EntityMobSkull.class, new RenderMobSkull(Minecraft.getMinecraft().getRenderManager(), seaserpent_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityShivaxiDragon.class, new RenderDragonBase(Minecraft.getMinecraft().getRenderManager(), lightningdragon_model));
		RenderingRegistry.registerEntityRenderingHandler(EntityShivaxiDragonLightning.class, new RenderNothing(Minecraft.getMinecraft().getRenderManager()));
		RenderingRegistry.registerEntityRenderingHandler(EntityDragonBreath.class, new RenderDragonBreath<>(Minecraft.getMinecraft().getRenderManager(), Minecraft.getMinecraft().getRenderItem()));

		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPodium.class, new RenderPodium());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityLectern.class, new RenderLectern());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityEggInIce.class, new RenderEggInIce());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityPixieHouse.class, new RenderPixieHouse());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityJar.class, new RenderJar());
		ClientRegistry.bindTileEntitySpecialRenderer(TileEntityGhostChest.class, new RenderGhostChest());
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.pixieHouse), 0, TileEntityPixieHouse.class);
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.pixieHouse), 1, TileEntityPixieHouse.class);
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.pixieHouse), 2, TileEntityPixieHouse.class);
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.pixieHouse), 3, TileEntityPixieHouse.class);
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.pixieHouse), 4, TileEntityPixieHouse.class);
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.pixieHouse), 5, TileEntityPixieHouse.class);
		ForgeHooksClient.registerTESRItemStack(Item.getItemFromBlock(IafBlockRegistry.ghost_chest), 0, TileEntityGhostChest.class);
	}
}